// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tea0112/omni-platform/services/identity/internal/role (interfaces: RoleRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repo_mock.go -package=mocks . RoleRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	role "github.com/tea0112/omni-platform/services/identity/internal/role"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// AddPermission mocks base method.
func (m *MockRoleRepository) AddPermission(ctx context.Context, roleID uuid.UUID, permission string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPermission", ctx, roleID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPermission indicates an expected call of AddPermission.
func (mr *MockRoleRepositoryMockRecorder) AddPermission(ctx, roleID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPermission", reflect.TypeOf((*MockRoleRepository)(nil).AddPermission), ctx, roleID, permission)
}

// AssignToUser mocks base method.
func (m *MockRoleRepository) AssignToUser(ctx context.Context, roleID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignToUser", ctx, roleID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignToUser indicates an expected call of AssignToUser.
func (mr *MockRoleRepositoryMockRecorder) AssignToUser(ctx, roleID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignToUser", reflect.TypeOf((*MockRoleRepository)(nil).AssignToUser), ctx, roleID, userID)
}

// Create mocks base method.
func (m *MockRoleRepository) Create(ctx context.Context, req role.CreateRoleRequest) (*role.RoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*role.RoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleRepositoryMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleRepository)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockRoleRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRoleRepository) GetByID(ctx context.Context, id uuid.UUID) (*role.RoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*role.RoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleRepository)(nil).GetByID), ctx, id)
}

// GetPermissions mocks base method.
func (m *MockRoleRepository) GetPermissions(ctx context.Context, roleID uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockRoleRepositoryMockRecorder) GetPermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockRoleRepository)(nil).GetPermissions), ctx, roleID)
}

// GetUserRoles mocks base method.
func (m *MockRoleRepository) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]role.RoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userID)
	ret0, _ := ret[0].([]role.RoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockRoleRepositoryMockRecorder) GetUserRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockRoleRepository)(nil).GetUserRoles), ctx, userID)
}

// List mocks base method.
func (m *MockRoleRepository) List(ctx context.Context) ([]role.RoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]role.RoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepository)(nil).List), ctx)
}

// RemoveFromUser mocks base method.
func (m *MockRoleRepository) RemoveFromUser(ctx context.Context, roleID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromUser", ctx, roleID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromUser indicates an expected call of RemoveFromUser.
func (mr *MockRoleRepositoryMockRecorder) RemoveFromUser(ctx, roleID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromUser", reflect.TypeOf((*MockRoleRepository)(nil).RemoveFromUser), ctx, roleID, userID)
}

// RemovePermission mocks base method.
func (m *MockRoleRepository) RemovePermission(ctx context.Context, roleID uuid.UUID, permission string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePermission", ctx, roleID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePermission indicates an expected call of RemovePermission.
func (mr *MockRoleRepositoryMockRecorder) RemovePermission(ctx, roleID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePermission", reflect.TypeOf((*MockRoleRepository)(nil).RemovePermission), ctx, roleID, permission)
}

// Update mocks base method.
func (m *MockRoleRepository) Update(ctx context.Context, id uuid.UUID, req role.UpdateRoleRequest) (*role.RoleRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*role.RoleRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoleRepositoryMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleRepository)(nil).Update), ctx, id, req)
}
